import { Flight, SeatMap, Seat, Booking, TicketVerification, AnalyticsDashboard } from '../types';

export const INITIAL_MOCK_FLIGHTS: Flight[] = [
  // 1. HYD -> VTZ Flight
  {
    id: 101,
    flightNumber: 'SN-701',
    airlineName: 'SkyNova Airways',
    airlineCode: 'SN',
    originAirportCode: 'HYD',
    originAirportName: 'Rajiv Gandhi International Airport',
    originCity: 'Hyderabad',
    destinationAirportCode: 'VTZ',
    destinationAirportName: 'Visakhapatnam International Airport',
    destinationCity: 'Visakhapatnam',
    aircraftModel: 'Airbus A320neo',
    departureTime: new Date(Date.now() + 36000000).toISOString(),
    arrivalTime: new Date(Date.now() + 36000000 + 4500000).toISOString(),
    durationMinutes: 75,
    basePrice: 120,
    calculatedFare: 134.4,
    taxAmount: 14.4,
    status: 'SCHEDULED',
    gateNumber: 'Gate 5',
    terminal: 'T1',
    availableSeats: 165,
    delayMinutes: 0,
  },
  // 2. VTZ -> HYD Flight
  {
    id: 102,
    flightNumber: 'SN-702',
    airlineName: 'SkyNova Airways',
    airlineCode: 'SN',
    originAirportCode: 'VTZ',
    originAirportName: 'Visakhapatnam International Airport',
    originCity: 'Visakhapatnam',
    destinationAirportCode: 'HYD',
    destinationAirportName: 'Rajiv Gandhi International Airport',
    destinationCity: 'Hyderabad',
    aircraftModel: 'Airbus A320neo',
    departureTime: new Date(Date.now() + 50000000).toISOString(),
    arrivalTime: new Date(Date.now() + 50000000 + 4500000).toISOString(),
    durationMinutes: 75,
    basePrice: 125,
    calculatedFare: 140,
    taxAmount: 15,
    status: 'SCHEDULED',
    gateNumber: 'Gate 2',
    terminal: 'T1',
    availableSeats: 170,
    delayMinutes: 0,
  },
  // 3. VGA (Gannavaram) -> BLR (Bangalore) Flight
  {
    id: 103,
    flightNumber: 'SN-703',
    airlineName: 'SkyNova Airways',
    airlineCode: 'SN',
    originAirportCode: 'VGA',
    originAirportName: 'Vijayawada International Airport (Gannavaram)',
    originCity: 'Vijayawada',
    destinationAirportCode: 'BLR',
    destinationAirportName: 'Kempegowda International Airport',
    destinationCity: 'Bengaluru',
    aircraftModel: 'Airbus A320neo',
    departureTime: new Date(Date.now() + 42000000).toISOString(),
    arrivalTime: new Date(Date.now() + 42000000 + 5400000).toISOString(),
    durationMinutes: 90,
    basePrice: 135,
    calculatedFare: 151.2,
    taxAmount: 16.2,
    status: 'SCHEDULED',
    gateNumber: 'Gate 3',
    terminal: 'T1',
    availableSeats: 150,
    delayMinutes: 0,
  },
  // 4. BLR (Bangalore) -> VGA (Gannavaram) Flight
  {
    id: 104,
    flightNumber: 'SN-704',
    airlineName: 'SkyNova Airways',
    airlineCode: 'SN',
    originAirportCode: 'BLR',
    originAirportName: 'Kempegowda International Airport',
    originCity: 'Bengaluru',
    destinationAirportCode: 'VGA',
    destinationAirportName: 'Vijayawada International Airport (Gannavaram)',
    destinationCity: 'Vijayawada',
    aircraftModel: 'Airbus A320neo',
    departureTime: new Date(Date.now() + 65000000).toISOString(),
    arrivalTime: new Date(Date.now() + 65000000 + 5400000).toISOString(),
    durationMinutes: 90,
    basePrice: 140,
    calculatedFare: 156.8,
    taxAmount: 16.8,
    status: 'SCHEDULED',
    gateNumber: 'Gate 14',
    terminal: 'T2',
    availableSeats: 155,
    delayMinutes: 0,
  },
  {
    id: 1,
    flightNumber: 'SN-101',
    airlineName: 'SkyNova Airways',
    airlineCode: 'SN',
    originAirportCode: 'JFK',
    originAirportName: 'John F. Kennedy International',
    originCity: 'New York',
    destinationAirportCode: 'LHR',
    destinationAirportName: 'London Heathrow',
    destinationCity: 'London',
    aircraftModel: 'Boeing 787-9 Dreamliner',
    departureTime: new Date(Date.now() + 86400000).toISOString(),
    arrivalTime: new Date(Date.now() + 86400000 + 25200000).toISOString(),
    durationMinutes: 420,
    basePrice: 450,
    calculatedFare: 504,
    taxAmount: 54,
    status: 'SCHEDULED',
    gateNumber: 'Gate 4B',
    terminal: 'T4',
    availableSeats: 185,
    delayMinutes: 0,
  },
  {
    id: 2,
    flightNumber: 'SN-102',
    airlineName: 'SkyNova Airways',
    airlineCode: 'SN',
    originAirportCode: 'LHR',
    originAirportName: 'London Heathrow',
    originCity: 'London',
    destinationAirportCode: 'JFK',
    destinationAirportName: 'John F. Kennedy International',
    destinationCity: 'New York',
    aircraftModel: 'Airbus A350-900',
    departureTime: new Date(Date.now() + 90000000).toISOString(),
    arrivalTime: new Date(Date.now() + 90000000 + 27000000).toISOString(),
    durationMinutes: 450,
    basePrice: 480,
    calculatedFare: 537.6,
    taxAmount: 57.6,
    status: 'SCHEDULED',
    gateNumber: 'Gate 22A',
    terminal: 'T5',
    availableSeats: 210,
    delayMinutes: 0,
  },
  {
    id: 3,
    flightNumber: 'SN-205',
    airlineName: 'SkyNova Airways',
    airlineCode: 'SN',
    originAirportCode: 'JFK',
    originAirportName: 'John F. Kennedy International',
    originCity: 'New York',
    destinationAirportCode: 'CDG',
    destinationAirportName: 'Charles de Gaulle',
    destinationCity: 'Paris',
    aircraftModel: 'Boeing 777-300ER',
    departureTime: new Date(Date.now() + 100000000).toISOString(),
    arrivalTime: new Date(Date.now() + 100000000 + 26000000).toISOString(),
    durationMinutes: 435,
    basePrice: 520,
    calculatedFare: 582.4,
    taxAmount: 62.4,
    status: 'BOARDING',
    gateNumber: 'Gate 12C',
    terminal: 'T1',
    availableSeats: 140,
    delayMinutes: 0,
  },
  {
    id: 4,
    flightNumber: 'SN-308',
    airlineName: 'SkyNova Airways',
    airlineCode: 'SN',
    originAirportCode: 'SFO',
    originAirportName: 'San Francisco International',
    originCity: 'San Francisco',
    destinationAirportCode: 'HND',
    destinationAirportName: 'Tokyo Haneda',
    destinationCity: 'Tokyo',
    aircraftModel: 'Boeing 787-9 Dreamliner',
    departureTime: new Date(Date.now() + 120000000).toISOString(),
    arrivalTime: new Date(Date.now() + 120000000 + 38400000).toISOString(),
    durationMinutes: 640,
    basePrice: 850,
    calculatedFare: 952,
    taxAmount: 102,
    status: 'SCHEDULED',
    gateNumber: 'Gate 91',
    terminal: 'INTL',
    availableSeats: 95,
    delayMinutes: 0,
  },
  {
    id: 5,
    flightNumber: 'SN-412',
    airlineName: 'SkyNova Airways',
    airlineCode: 'SN',
    originAirportCode: 'DXB',
    originAirportName: 'Dubai International',
    originCity: 'Dubai',
    destinationAirportCode: 'SIN',
    destinationAirportName: 'Singapore Changi',
    destinationCity: 'Singapore',
    aircraftModel: 'Airbus A350-900',
    departureTime: new Date(Date.now() + 140000000).toISOString(),
    arrivalTime: new Date(Date.now() + 140000000 + 28800000).toISOString(),
    durationMinutes: 480,
    basePrice: 620,
    calculatedFare: 694.4,
    taxAmount: 74.4,
    status: 'SCHEDULED',
    gateNumber: 'Gate B14',
    terminal: 'T3',
    availableSeats: 160,
    delayMinutes: 0,
  },
  {
    id: 6,
    flightNumber: 'SN-501',
    airlineName: 'SkyNova Airways',
    airlineCode: 'SN',
    originAirportCode: 'DEL',
    originAirportName: 'Indira Gandhi International',
    originCity: 'New Delhi',
    destinationAirportCode: 'LHR',
    destinationAirportName: 'London Heathrow',
    destinationCity: 'London',
    aircraftModel: 'Boeing 787-9 Dreamliner',
    departureTime: new Date(Date.now() + 160000000).toISOString(),
    arrivalTime: new Date(Date.now() + 160000000 + 32400000).toISOString(),
    durationMinutes: 540,
    basePrice: 710,
    calculatedFare: 795.2,
    taxAmount: 85.2,
    status: 'SCHEDULED',
    gateNumber: 'Gate 18',
    terminal: 'T3',
    availableSeats: 110,
    delayMinutes: 0,
  }
];

export const generateSeatMap = (flightId: number, flightNumber: string, aircraftModel: string): SeatMap => {
  const seats: Seat[] = [];
  const cols = ['A', 'B', 'C', 'D', 'E', 'F'];

  // Rows 1-2: First Class
  for (let row = 1; row <= 2; row++) {
    ['A', 'B', 'E', 'F'].forEach((col) => {
      seats.push({
        id: flightId * 1000 + row * 10 + col.charCodeAt(0),
        seatNumber: `${row}${col}`,
        seatRow: row,
        seatColumn: col,
        cabinClass: 'FIRST_CLASS',
        isWindow: col === 'A' || col === 'F',
        isAisle: col === 'B' || col === 'E',
        isExitRow: false,
        extraLegroom: true,
        isOccupied: row === 1 && col === 'A',
        isBlocked: false,
        seatSurcharge: 50.0,
      });
    });
  }

  // Rows 3-6: Business Class
  for (let row = 3; row <= 6; row++) {
    cols.forEach((col) => {
      seats.push({
        id: flightId * 1000 + row * 10 + col.charCodeAt(0),
        seatNumber: `${row}${col}`,
        seatRow: row,
        seatColumn: col,
        cabinClass: 'BUSINESS',
        isWindow: col === 'A' || col === 'F',
        isAisle: col === 'C' || col === 'D',
        isExitRow: false,
        extraLegroom: true,
        isOccupied: (row === 3 && col === 'B') || (row === 4 && col === 'C'),
        isBlocked: false,
        seatSurcharge: 30.0,
      });
    });
  }

  // Rows 7-25: Economy Class
  for (let row = 7; row <= 25; row++) {
    cols.forEach((col) => {
      const isExit = row === 12;
      const legroom = isExit;
      let surcharge = 0;
      if (legroom) surcharge += 25;
      if (col === 'A' || col === 'F') surcharge += 10;

      seats.push({
        id: flightId * 1000 + row * 10 + col.charCodeAt(0),
        seatNumber: `${row}${col}`,
        seatRow: row,
        seatColumn: col,
        cabinClass: 'ECONOMY',
        isWindow: col === 'A' || col === 'F',
        isAisle: col === 'C' || col === 'D',
        isExitRow: isExit,
        extraLegroom: legroom,
        isOccupied: (row === 12 && col === 'A') || (row === 14 && col === 'F') || (row === 18 && col === 'C'),
        isBlocked: false,
        seatSurcharge: surcharge,
      });
    });
  }

  return {
    flightId,
    flightNumber,
    aircraftModel,
    seats,
  };
};
